### ISSUE TITLE
Login isn't working

### ISSUE THREAD

**Issue by danielnbalasoiu** [savegame/harbour-mattermost#1]
Application fails to login to remote server.

Steps to reproduce:
1. open harbour-mattermost app
2. fill in all required fields (server custom name, server address, Username or Email address, Password)
3. Press `Login` button

Expected result: login to mattermost server
Actual result: Loading icon is spinning continuously  with no result.
Device: Sony Xperia 10

```
,---
| Sailfish OS 3.2.1.20 (Nuuksio)
'---
[nemo@Sailfish ~]$ harbour-mattermost 
Debug: Using Wayland-EGL ((null):0, (null))
Debug: App version:  0.1.3 ((null):0, (null))
Info: Path to CA certificate file is empty ((null):0, (null))
Info: Path to certificate file is empty ((null):0, (null))
Warning: Failure:  QNetworkReply::NetworkError(ProtocolUnknownError) "Protocol \"\" is unknown" ((null):0, (null))
Debug: QNetworkReplyImpl(0xad39eb78) ((null):0, (null))
Warning: Failure:  QNetworkReply::NetworkError(ProtocolUnknownError) "Protocol \"\" is unknown" ((null):0, (null))
Debug: QNetworkReplyImpl(0xad4c33a8) ((null):0, (null))
Warning: Failure:  QNetworkReply::NetworkError(ProtocolUnknownError) "Protocol \"\" is unknown" ((null):0, (null))
Debug: QNetworkReplyImpl(0xad4e5e80) ((null):0, (null))
Warning: Failure:  QNetworkReply::NetworkError(ProtocolUnknownError) "Protocol \"\" is unknown" ((null):0, (null))
Debug: QNetworkReplyImpl(0xad418e80) ((null):0, (null))
```
It fails with and without enabling "trust certificate" option.

**Comment by savegame** [comment]
do you add **http** or **https** in your servers address? 
as i understand, message like `QNetworkReply::NetworkError(ProtocolUnknownError)` - this say - you fogot set **http** or **https**  in address.
and here only mirror of harbour-mattermost repo, origina repo is on [gitlab.com](https://gitlab.com/sashikknox/harbour-mattermost)

**Comment by danielnbalasoiu** [comment]
Yes, I've added **https://** in from of the domain address.
I missed the notification for this issue. Sorry for late reply.

**Comment by savegame** [comment]
Issue moved to GitLAb
